### ISSUE TITLE
Method : s3.del() not working 

### ISSUE THREAD

**Issue by anil826** [SaltwaterC/aws2js#91]
// relative_path = https://xxxxx.amazonaws.com/xxxxx/xxxx/7f77dbbc-0c8d/archive.mp4

 s3.del(relative_path, function(error,data){
    if(error) return res.json(500, error);
    res.json({data: data})
  })

API response:
---------------------
{
    "data": {
        "x-amz-id-2": "0gnrIyCkAitotK6XcTkFdvX8=",
        "x-amz-request-id": "xxxxxxxxx",
        "date": "Thu, 24 Nov 2016 08:01:16 GMT",
        "server": "AmazonS3",
        "connection": "close"
    }
}
Am I doing something wrong here?

**Comment by SaltwaterC** [comment]
Hi,

Most probably you're not doing anything wrong, but the library hasn't been
maintained for quite a while. Amazon is providing an official SDK which is
the recommended option these days.

Cheers.
