### ISSUE TITLE
Trying to stream mysqlbinlog to S3

### ISSUE THREAD

**Issue by sastryraghu** [SaltwaterC/aws2js#92]
Hello,  I am trying to stream mysql binary logs using mysqlbinlog utility. However, I dont see the files being written to s3. Can you let usknow  if this is not allowed? (mysqlbinlog utility reads binary logs from the master and creates a file . Instead, I am trying to stream to s3.)

 `mysqlbinlog --read-from-remote-server --host=10.2.1.5 --port=3306  --user=userrepl --password=xxxxx --stop-never mysqld-bin.000514  | /root/.local/lib/aws/bin/aws s3 cp - s3://bucket/binlog/m1/ &
`

Thanks a lot!
Regards,
Raghu

**Comment by SaltwaterC** [comment]
Hi Raghu,

This isn't the right project to ask this question I'm afraid. This is an AWS library written in JavaScript for node.js. In your example you're using the [aws-cli](https://github.com/aws/aws-cli) command which by my knowledge is still written in Python. I don't know whether it supports STDIN as I've never used it in pipes.

In any case, this library isn't maintained anymore as it would have been a full-time job. I do recommend people to use: https://github.com/aws/aws-sdk-js

Best regards,
Ștefan
